name: "Test wangvnn-github-actions"

on:
  push:
  pull_request:
    branches: [wangvn-patch1]

defaults:
  run:
    shell: bash

jobs:
  clone-and-install:  
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
    container: ubuntu:bionic
      
    steps:    
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
