name: "Test wangvnn-github-actions"

on:
  push:
  pull_request:
    branches: [wangvn-patch1]

defaults:
  run:
    shell: bash

jobs:
  clone-and-install:  
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
    container: ubuntu:bionic
      
    steps:    
    # Checkout SA ros1 branch into sample folder
    - name: Checkout hello world sample app
      uses: actions/checkout@v2
      with:
        repository: aws-robotics/aws-robomaker-sample-application-helloworld
        path: sample
        ref: ros1
    - run: ls
